# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [2]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [3]:
a = range(10,50)
V = np.array(a)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [4]:
Rvs_V = V[::-1]
print(Rvs_V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [5]:
a = np.array(range(9))
mat = a.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [6]:
a = np.array([1,2,0,0,4,0])
a[np.nonzero(a)]

array([1, 2, 4])

#### 6. Create a 3x3 identity matrix 

In [7]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 7. Create a 3x3x3 array with random values 

In [8]:
np.random.random((3,3,3))

array([[[0.46488997, 0.76610139, 0.18865474],
        [0.57708027, 0.55849051, 0.8575289 ],
        [0.33605557, 0.9634768 , 0.65709882]],

       [[0.37223221, 0.52217885, 0.88727506],
        [0.62112325, 0.1269052 , 0.26212083],
        [0.51169481, 0.80948567, 0.68319311]],

       [[0.21100373, 0.09242576, 0.60518316],
        [0.67643576, 0.55451689, 0.94385359],
        [0.38163868, 0.65083538, 0.30834872]]])

#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [9]:
np.random.seed(0)
v = np.random.random((10,10))
print(np.min(v),'\n',np.max(v))

0.004695476192547066 
 0.9883738380592262


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [10]:
a = np.array([[0,1],[1,0]])
Checkerboard = np.tile(a,(4,4))
print(Checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [11]:
np.random.seed(0)
a = np.random.rand(5,3)
b = np.random.rand(3,2)
a @ b

array([[1.16771006, 1.15750086],
       [0.96215441, 0.97277033],
       [1.61903287, 1.64584455],
       [1.15275998, 1.14142503],
       [0.88196569, 0.80126141]])

#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [12]:
a = np.array(range(5))
np.tile(a,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [13]:
np.zeros((5,5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 13. Create a random vector of size 10 and sort it 

In [14]:
a = np.random.rand(10)
np.sort(a,axis=0)

array([0.11827443, 0.14335329, 0.26455561, 0.41466194, 0.46147936,
       0.52184832, 0.63992102, 0.78052918, 0.79915856, 0.94466892])

#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [15]:
np.random.seed(0)
x = np.random.rand(5,10) 
#print(x)
#b = []

#for문을 사용하지 않고 풀 방법은 없을까???
#for i in range(len(x)) :
#    a = x[i] - np.mean(x[i])
#   b.append(a)
#print(b)

avg = x.mean(axis = 1).reshape(5,1)
c = x -avg
print(c)

[[-0.06695278  0.09942308 -0.01300291 -0.0708831  -0.19211148  0.03012783
  -0.17817907  0.27600672  0.34789648 -0.23232476]
 [ 0.24438167 -0.01844845  0.0207012   0.37825327 -0.47630731 -0.46021407
  -0.52712497  0.28527648  0.23081339  0.32266878]
 [ 0.39836701  0.21890723 -0.11877197  0.20027784 -0.46197691  0.05966969
  -0.43689805  0.36441758 -0.05840301 -0.1655894 ]
 [-0.29088409  0.21879399 -0.09928937  0.01299425 -0.5366499   0.0621958
   0.05665602  0.0614943   0.38830838  0.1263806 ]
 [-0.03151701  0.04600705  0.30660629 -0.33079944  0.27574181  0.27961296
  -0.18064235 -0.26209861 -0.07559656 -0.02731414]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [16]:
a = np.array([range(1,11)])
b = np.tile(a,(10,1))
c = a.transpose()
b * c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [17]:
np.random.seed(0)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

print(np.diag(A.dot(B)))
print(np.diag(np.diag(A.dot(B))))

[1.39270148 1.47905707 1.99450313 1.16403584 1.29890636]
[[1.39270148 0.         0.         0.         0.        ]
 [0.         1.47905707 0.         0.         0.        ]
 [0.         0.         1.99450313 0.         0.        ]
 [0.         0.         0.         1.16403584 0.        ]
 [0.         0.         0.         0.         1.29890636]]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [18]:
a = np.array([1,2,3,4,5])
b = np.zeros((len(a)+3*(len(a)-1)),)
b[::4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [30]:
#모르겠음

np.random.seed(0)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [20]:
a = np.array(range(25)).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [21]:
np.random.seed(0)
a = np.random.randint(0,10,50)
print(a)
counts = np.bincount(a)
print(counts)
print(np.argmax(counts))

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3 3
 7 0 1 9 9 0 4 7 3 2 7 2 0]
[ 6  4  4 10  3  4  2  7  5  5]
3


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [27]:
np.random.seed(0)
Z = np.arange(10000);
np.random.shuffle(Z)
n = int(input("Enter the number : "))
print(Z[Z.argsort()[-n]])

Enter the number : 40
9960


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [29]:
T = np.random.randint(2,size=21).reshape(7,3)

print(T)

unq_rows = np.unique(T, axis=0)
print(unq_rows)

[[0 1 0]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [24]:
def moving_avg(arr, n) :
    import numpy as np
    for i in range(len(arr) - n +1) :
        print(np.mean(arr[i:i+n]))
moving_avg([1,2,3,4,5],4)

2.5
3.5


#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [25]:
np.random.seed(0)
a = np.random.rand(4,4)
print(a)
print(*zip(np.nonzero(a>0.5)[0],np.nonzero(a>0.5)[1]))

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]
(0, 0) (0, 1) (0, 2) (0, 3) (1, 1) (1, 3) (2, 0) (2, 2) (2, 3) (3, 0) (3, 1)


#### 25. Write a function returning distance between two points

In [26]:
def distance (x,y) :
    b = []
    for i in range(len(x)) :
        a = float((x[i] - y[i])**2)
        b.append(a)
    b = np.array(b)
    print(np.sqrt(b.sum()))
distance([0,1,0],[3,5,4])

6.4031242374328485
